### ISSUE TITLE
Implement highlight window and log

### ISSUE THREAD

**Issue by KeiroD** [OmegaPhil/kvirc-highlight-management-script#1]
Is it possible to include a highlight window that all the highlights go to and to have the highlights also be logged?

**Comment by OmegaPhil** [comment]
Hmm, feature request-wise this is fine even though it is out of scope of blacklisting, but I'm not planning on doing any more work on this script in general, so it will take a long time to reach this.

**Comment by KeiroD** [comment]
Understood. In that case, I will fork this repository and attempt to add it myself and submit a PR once I figure out how to do KVS properly. :)

**Comment by OmegaPhil** [comment]
OK, to be honest I think I fork and no PR would be easier - I'd still need to review the pull, and would undoubtedly want to have 'my style', and I also wouldn't know how to do things so would require research by me. Maybe something in the future if highlighting becomes more important to me.

**Comment by KeiroD** [comment]
Works for me, either way. :)

**Comment by OmegaPhil** [comment]
Keep me informed if you release something, I'll mention in the docs here.

**Comment by OmegaPhil** [comment]
Looks like you haven't made the fork - I have finally reached this task now.

**Comment by OmegaPhil** [comment]
@KeiroD: Take a look at the new branch: https://github.com/OmegaPhil/kvirc-highlight-management-script/tree/highlight-window

We now have a Highlight Log window and its logged to file in the usual KVIrc log directory. Follow the normal installation instructions to upgrade, theres a new 'Configure Highlight Log window...' option in the script settings, although the defaults are sane.

If you're OK with it/ a week times out, I'll push it as the next version.

**Comment by OmegaPhil** [comment]
Note with the push I made just now, I have added separate username blacklisting functionality, so you'll need to go through the install procedure again if you've not done it before. This is the last change I'm expecting to make for now.

**Comment by OmegaPhil** [comment]
Fixed now that v1.4 is live.
